media:
  input: "images"
  output: "images"

content:
  - name: homepage
    label: "Главная страница"
    type: file
    path: "index.html"
    fields:
      - name: body
        label: "Содержимое"
        type: text

  - name: about
    label: "Обо мне"
    type: file
    path: "about.html"
    fields:
      - name: body
        label: "Содержимое"
        type: text

  - name: services
    label: "Услуги"
    type: file
    path: "services.html"
    fields:
      - name: body
        label: "Содержимое"
        type: text

  - name: blog
    label: "Блог"
    type: collection
    path: "blog"
    view:
      fields: [title, date]
    fields:
      - name: title
        label: "Заголовок статьи"
        type: string
      - name: date
        label: "Дата"
        type: date
      - name: body
        label: "Текст статьи"
        type: rich-text
